services:
  api:
    container_name: api
    build:
      context: ../..
      dockerfile: ./SFServer.API/Dockerfile
    restart: unless-stopped
    environment:
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION}
      ASPNETCORE_ENVIRONMENT: ${ENVIRONMENT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_TIMEOUT_HOURS: ${JWT_TIMEOUT_HOURS}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    volumes:
      - datakeys:/var/app-keys
    networks:
      - shared-net
    ports:
      - "${API_PORT}:8080"

  ui:
    container_name: ui
    build:
      context: ../..
      dockerfile: ./SFServer.UI/Dockerfile_Dev
    restart: unless-stopped
    volumes:
      - datakeys:/var/app-keys
    ports:
      - "${UI_PORT}:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ENVIRONMENT}
      SERVER_COPYRIGHT: ${SERVER_COPYRIGHT}
      SERVER_TITLE: ${SERVER_TITLE}
      API_BASE_URL: ${API_BASE_URL}
      JS_API_BASE_URL: ${JS_API_BASE_URL}
    networks:
      - shared-net
    depends_on:
      api:
        condition: service_started

networks:
  shared-net:
    external: true
      
volumes:
  datakeys:
