// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SFServer.API.Data;

#nullable disable

namespace SFServer.API.Migrations
{
    [DbContext(typeof(DatabseContext))]
    [Migration("20250610225613_AddConfigFiles")]
    partial class AddConfigFiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("UserProfileIndex", "dbo");

            modelBuilder.Entity("SFServer.Shared.Server.Configs.ConfigFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigMetadataId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("S3Key")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConfigMetadataId");

                    b.ToTable("ConfigFiles");
                });

            modelBuilder.Entity("SFServer.Shared.Server.Configs.ConfigMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("SFServer.Shared.Server.Settings.ServerSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessKeyId")
                        .HasColumnType("text");

                    b.Property<string>("Bucket")
                        .HasColumnType("text");

                    b.Property<string>("GoogleClientId")
                        .HasColumnType("text");

                    b.Property<string>("GoogleClientSecret")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<string>("SecretAccessKey")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ServerSettings");
                });

            modelBuilder.Entity("SFServer.Shared.Server.UserProfile.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<string>("DeviceModel")
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text");

                    b.Property<bool>("FullScreen")
                        .HasColumnType("boolean");

                    b.Property<string>("GraphicsDeviceName")
                        .HasColumnType("text");

                    b.Property<string>("GraphicsDeviceType")
                        .HasColumnType("text");

                    b.Property<string>("GraphicsDeviceVendor")
                        .HasColumnType("text");

                    b.Property<string>("GraphicsDeviceVersion")
                        .HasColumnType("text");

                    b.Property<int>("GraphicsMemorySize")
                        .HasColumnType("integer");

                    b.Property<string>("GraphicsShaderLevel")
                        .HasColumnType("text");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("text");

                    b.Property<int>("ProcessorCount")
                        .HasColumnType("integer");

                    b.Property<string>("ProcessorType")
                        .HasColumnType("text");

                    b.Property<float>("ScreenDpi")
                        .HasColumnType("real");

                    b.Property<int>("ScreenHeight")
                        .HasColumnType("integer");

                    b.Property<int>("ScreenWidth")
                        .HasColumnType("integer");

                    b.Property<int>("SystemMemorySize")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("UserDevices");
                });

            modelBuilder.Entity("SFServer.Shared.Server.UserProfile.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DebugMode")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("DeviceIds")
                        .HasColumnType("text[]");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("GooglePlayId")
                        .HasColumnType("text");

                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Index"));

                    b.Property<DateTime>("LastEditAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("SFServer.Shared.Server.Wallet.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<int>("InitialAmount")
                        .HasColumnType("integer");

                    b.Property<int>("RefillSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("RichText")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("SFServer.Shared.Server.Wallet.WalletItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("WalletItems");
                });

            modelBuilder.Entity("SFServer.Shared.Server.Configs.ConfigFile", b =>
                {
                    b.HasOne("SFServer.Shared.Server.Configs.ConfigMetadata", null)
                        .WithMany("Files")
                        .HasForeignKey("ConfigMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SFServer.Shared.Server.Wallet.WalletItem", b =>
                {
                    b.HasOne("SFServer.Shared.Server.Wallet.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("SFServer.Shared.Server.Configs.ConfigMetadata", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
